######################################################################
# Automatically generated by qmake (3.0) ?? 10? 19 21:47:58 2013
######################################################################

TEMPLATE = app
TARGET = templateMethod
INCLUDEPATH += .
CONFIG = warn_on debug 
INCLUDEPATH
LIBS


# Input
HEADERS += TemplateMethodMain.h TestPaper.h TestPaperA.h TestPaperB.h
SOURCES += TemplateMethodMain.cpp TestPaper.cpp TestPaperA.cpp TestPaperB.cpp
