######################################################################
# Automatically generated by qmake (1.07a) Sat Sep 7 01:36:27 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Api.h Client.h Factory.h ImplA.h ImplB.h
SOURCES += Api.cpp Client.cpp Factory.cpp ImplA.cpp ImplB.cpp
