######################################################################
# Automatically generated by qmake (1.07a) Sat Sep 7 22:47:16 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Api.h Client.h Factory.h Impl.h
SOURCES += Api.cpp Client.cpp Factory.cpp Impl.cpp
