######################################################################
# Automatically generated by qmake (1.07a) Sun Sep 8 00:50:02 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Client.h FeeRequest.h
SOURCES += Client.cpp FeeRequest.cpp
