######################################################################
# Automatically generated by qmake (3.0) ?? 10? 16 23:30:21 2013
######################################################################

TEMPLATE = app
TARGET = adapter
INCLUDEPATH += .

# Input
HEADERS += AdapterMain.h Center.h Guard.h Player.h Translator.h
SOURCES += AdapterMain.cpp Center.cpp Guard.cpp Player.cpp Translator.cpp
