######################################################################
# Automatically generated by qmake (3.0) ?? 9? 27 20:44:45 2013
######################################################################

TEMPLATE = app
TARGET = example1
INCLUDEPATH += .

# Input
HEADERS += AppConfig.h Client.h
SOURCES += AppConfig.cpp Client.cpp
