######################################################################
# Automatically generated by qmake (3.0) ?? 10? 18 02:28:25 2013
######################################################################

TEMPLATE = app
TARGET = interpreter
INCLUDEPATH += .
CONFIG = warn_on debug 
INCLUDEPATH
LIBS


# Input
HEADERS += Expression.h InterpreterMain.h Note.h PlayContext.h Scale.h
SOURCES += Expression.cpp InterpreterMain.cpp Note.cpp PlayContext.cpp Scale.cpp
