######################################################################
# Automatically generated by qmake (3.0) ?? 10? 18 13:48:05 2013
######################################################################

TEMPLATE = app
TARGET = proxy
INCLUDEPATH += .
CONFIG = warn_on debug 
INCLUDEPATH
LIBS


# Input
HEADERS += GiveGift.h Proxy.h ProxyMain.h Pursuit.h SchoolGirl.h
SOURCES += GiveGift.cpp Proxy.cpp ProxyMain.cpp Pursuit.cpp SchoolGirl.cpp
