/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_misoo_gx05_NativeJniAdder */

#ifndef _Included_com_misoo_gx05_NativeJniAdder
#define _Included_com_misoo_gx05_NativeJniAdder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_misoo_gx05_NativeJniAdder
 * Method:    calculate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_misoo_gx05_NativeJniAdder_calculate
(JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
