######################################################################
# Automatically generated by qmake (3.0) ?? 10? 18 12:14:37 2013
######################################################################

TEMPLATE = app
TARGET = memento
INCLUDEPATH += .
CONFIG = warn_on debug 
INCLUDEPATH
LIBS


# Input
HEADERS += CareTaker.h GameRole.h Memento.h MomentoMain.h
SOURCES += CareTaker.cpp GameRole.cpp Memento.cpp MomentoMain.cpp
