######################################################################
# Automatically generated by qmake (1.07a) Sun Sep 8 00:29:13 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Client.h Command.h ConcreteCommand.h Invoker.h Receiver.h
SOURCES += Client.cpp Command.cpp ConcreteCommand.cpp Invoker.cpp Receiver.cpp
