######################################################################
# Automatically generated by qmake (3.0) ?? 10? 26 01:44:48 2013
######################################################################

TEMPLATE = app
TARGET = facade
INCLUDEPATH += .
CONFIG = warn_on debug 
INCLUDEPATH
LIBS


# Input
HEADERS += FacadeMain.h Fund.h Stock1.h Stock2.h
SOURCES += FacadeMain.cpp Fund.cpp Stock1.cpp Stock2.cpp
