/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_misoo_service_counternative */

#ifndef _Included_com_misoo_service_counternative
#define _Included_com_misoo_service_counternative
#ifdef __cplusplus

extern "C" {
#endif

/*
 * Class:     com_misoo_service_counternative
 * Method:    execute
 * Signature: (I)I
 */

JNIEXPORT jint JNICALL Java_com_misoo_service_counternative_execute
(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
