######################################################################
# Automatically generated by qmake (1.07a) Sun Sep 8 00:46:21 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Client.h CommonMessageEmail.h CommonMessageSMS.h Message.h
SOURCES += Client.cpp CommonMessageEmail.cpp CommonMessageSMS.cpp Message.cpp
